parameters:
    spiriit_form_filter.data_collector.class: Spiriit\Bundle\FormFilterBundle\DataCollector\FilterDataCollector

services:
    spiriit_form_filter.data_collector:
        class: '%spiriit_form_filter.data_collector.class%'
        tags:
            - { name: data_collector, template: '@SpiriitFormFilter/Collector/filter.html.twig', id: 'spiriit_form_filter', priority: 245 }
            - { name: kernel.event_subscriber }
            - { name: kernel.reset, method: reset }
