name: Coding Standards

on:
  pull_request:
  push:

jobs:
    coding-standards:
        runs-on: ${{ matrix.operating-system }}
        strategy:
            matrix:
                operating-system: [ubuntu-latest]
                php-versions: ['8.5']
        name: PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}

        steps:
            - name: Checkout
              uses: actions/checkout@v7
              with:
                  fetch-depth: 2

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: json, mbstring, openssl, sqlite3
                  coverage: none

            - name: Install Composer dependencies
              run: composer update --prefer-dist --no-progress

            - name: CODING STANDARDS (ECS)
              run: vendor/bin/ecs check

            - name: CODING STANDARDS (RECTOR)
              run: vendor/bin/rector process --ansi --dry-run
